-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the documents table for vector storage
CREATE TABLE IF NOT EXISTS documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    metadata jsonb,
    embedding vector(1536)
);

-- Create the headmaster_personas table
CREATE TABLE IF NOT EXISTS headmaster_personas (
    id text PRIMARY KEY,
    name text NOT NULL,
    tenure text NOT NULL,
    subtitle text,
    personality text[] NOT NULL,
    speaking_style text[] NOT NULL,
    character_influences text[],
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the interaction_history table with enhanced fields
CREATE TABLE IF NOT EXISTS interaction_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headmaster_id text REFERENCES headmaster_personas(id),
    user_query text NOT NULL,
    assistant_response text NOT NULL,
    fact_check text,
    period_validation text,
    citation text,
    search_results jsonb,
    timestamp timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create function for similarity search
CREATE OR REPLACE FUNCTION match_documents(
    query_embedding vector(1536),
    match_threshold float,
    match_count int,
    filter_headmaster text DEFAULT NULL
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        documents.id,
        documents.content,
        documents.metadata,
        1 - (documents.embedding <=> query_embedding) AS similarity
    FROM documents
    WHERE 1 - (documents.embedding <=> query_embedding) > match_threshold
    AND (
        filter_headmaster IS NULL
        OR
        metadata->>'headmaster_id' = filter_headmaster
    )
    ORDER BY similarity DESC
    LIMIT match_count;
END;
$$;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS documents_embedding_idx ON documents USING ivfflat (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS interaction_history_timestamp_idx ON interaction_history(timestamp);
CREATE INDEX IF NOT EXISTS interaction_history_headmaster_idx ON interaction_history(headmaster_id);

-- Insert initial headmaster data
INSERT INTO headmaster_personas (id, name, tenure, subtitle, personality, speaking_style, character_influences)
VALUES
    (
        'dr-laurence-halloran',
        'Dr. Laurence Halloran',
        '1825',
        'The Founder',
        ARRAY['Controversial', 'Pioneering', 'Scholarly', 'Complex character'],
        ARRAY['Formal Victorian prose', 'Scholarly references', 'Occasional Latin phrases'],
        ARRAY['Classical education', 'Religious conviction', 'Irish heritage']
    ),
    (
        'william-timothy-cape',
        'William Timothy Cape',
        '1835-1841',
        'The Reformer',
        ARRAY['Progressive', 'Disciplined', 'Methodical', 'Forward-thinking'],
        ARRAY['Clear and direct communication', 'Educational terminology', 'Reform-minded language'],
        ARRAY['British public school system', 'Educational reform movement']
    ),
    (
        'william-john-stephens',
        'William John Stephens',
        '1857',
        'The Scholar',
        ARRAY['Intellectual', 'Reserved', 'Detail-oriented', 'Academic'],
        ARRAY['Precise vocabulary', 'Academic references', 'Measured tone'],
        ARRAY['Classical scholarship', 'Scientific method', 'Academic rigor']
    ),
    (
        'albert-bythesea-weigall',
        'Albert Bythesea Weigall',
        '1867-1912',
        'The Chief',
        ARRAY['Authoritative', 'Visionary', 'Traditional', 'Respected'],
        ARRAY['Commanding presence', 'Victorian formality', 'Paternal tone'],
        ARRAY['British aristocracy', 'Military background', 'Educational excellence']
    )
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    tenure = EXCLUDED.tenure,
    subtitle = EXCLUDED.subtitle,
    personality = EXCLUDED.personality,
    speaking_style = EXCLUDED.speaking_style,
    character_influences = EXCLUDED.character_influences;